-- ========================================================
-- BlogVerse — Complete Supabase Database Schema
-- Run this script in the Supabase SQL Editor:
-- Dashboard -> SQL Editor -> New query -> Paste & Run
-- ========================================================

-- 1. Enable UUID Extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- 2. Create Categories Table
CREATE TABLE IF NOT EXISTS public.categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    slug TEXT NOT NULL UNIQUE,
    description TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create Blogs Table
CREATE TABLE IF NOT EXISTS public.blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    excerpt TEXT DEFAULT '',
    author_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    author_name TEXT NOT NULL DEFAULT 'Anonymous',
    category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
    status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('draft', 'published')),
    featured_image TEXT DEFAULT '',
    tags TEXT DEFAULT '',
    likes_count INTEGER DEFAULT 0,
    views_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 4. Create Comments Table
CREATE TABLE IF NOT EXISTS public.comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blog_id BIGINT REFERENCES public.blogs(id) ON DELETE CASCADE NOT NULL,
    author_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    author_name TEXT NOT NULL DEFAULT 'Reader',
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 5. Create Likes Table
CREATE TABLE IF NOT EXISTS public.likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blog_id BIGINT REFERENCES public.blogs(id) ON DELETE CASCADE NOT NULL,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
    CONSTRAINT unique_blog_user_like UNIQUE (blog_id, user_id)
);

-- 6. Create Quickstart 'todos' Table (for initial test page verification)
CREATE TABLE IF NOT EXISTS public.todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    is_complete BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- ========================================================
-- Row Level Security (RLS) Policies
-- ========================================================

-- Enable RLS on all tables
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.todos ENABLE ROW LEVEL SECURITY;

-- Categories Policies (Anyone can read, authenticated can insert/update)
DROP POLICY IF EXISTS "Allow public read on categories" ON public.categories;
CREATE POLICY "Allow public read on categories" ON public.categories
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow authenticated insert categories" ON public.categories;
CREATE POLICY "Allow authenticated insert categories" ON public.categories
    FOR INSERT TO authenticated WITH CHECK (true);

-- Blogs Policies
-- 1. Anyone can view published blogs
DROP POLICY IF EXISTS "Allow public read published blogs" ON public.blogs;
CREATE POLICY "Allow public read published blogs" ON public.blogs
    FOR SELECT USING (status = 'published' OR (auth.uid() IS NOT NULL AND auth.uid() = author_id));

-- 2. Authenticated users can insert blogs
DROP POLICY IF EXISTS "Allow authenticated insert blogs" ON public.blogs;
CREATE POLICY "Allow authenticated insert blogs" ON public.blogs
    FOR INSERT TO authenticated WITH CHECK (auth.uid() = author_id OR author_id IS NULL);

-- 3. Authors can update their own blogs
DROP POLICY IF EXISTS "Allow authors update own blogs" ON public.blogs;
CREATE POLICY "Allow authors update own blogs" ON public.blogs
    FOR UPDATE USING (auth.uid() = author_id);

-- 4. Authors can delete their own blogs
DROP POLICY IF EXISTS "Allow authors delete own blogs" ON public.blogs;
CREATE POLICY "Allow authors delete own blogs" ON public.blogs
    FOR DELETE USING (auth.uid() = author_id);

-- Comments Policies
-- Anyone can view comments
DROP POLICY IF EXISTS "Allow public read comments" ON public.comments;
CREATE POLICY "Allow public read comments" ON public.comments
    FOR SELECT USING (true);

-- Authenticated can insert comments
DROP POLICY IF EXISTS "Allow authenticated insert comments" ON public.comments;
CREATE POLICY "Allow authenticated insert comments" ON public.comments
    FOR INSERT TO authenticated WITH CHECK (true);

-- Comment authors can delete their own comments
DROP POLICY IF EXISTS "Allow authors delete own comments" ON public.comments;
CREATE POLICY "Allow authors delete own comments" ON public.comments
    FOR DELETE USING (auth.uid() = author_id);

-- Likes Policies
DROP POLICY IF EXISTS "Allow public read likes" ON public.likes;
CREATE POLICY "Allow public read likes" ON public.likes
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow authenticated insert likes" ON public.likes;
CREATE POLICY "Allow authenticated insert likes" ON public.likes
    FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "Allow authenticated delete own likes" ON public.likes;
CREATE POLICY "Allow authenticated delete own likes" ON public.likes
    FOR DELETE USING (auth.uid() = user_id);

-- Todos Policies (Public read/insert for testing)
DROP POLICY IF EXISTS "Allow public read todos" ON public.todos;
CREATE POLICY "Allow public read todos" ON public.todos
    FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert todos" ON public.todos;
CREATE POLICY "Allow public insert todos" ON public.todos
    FOR INSERT WITH CHECK (true);

-- ========================================================
-- Seed Data
-- ========================================================

-- Insert Sample Categories
INSERT INTO public.categories (name, slug, description)
VALUES 
    ('Technology', 'technology', 'Latest in tech, programming, and innovation'),
    ('Travel', 'travel', 'Travel guides, tips, and adventures'),
    ('Lifestyle', 'lifestyle', 'Health, wellness, and daily living'),
    ('Science', 'science', 'Scientific discoveries and research'),
    ('Design', 'design', 'UI/UX, graphic design, and creative arts')
ON CONFLICT (slug) DO NOTHING;

-- Insert Sample Todos
INSERT INTO public.todos (name, is_complete)
VALUES
    ('Set up Supabase database connection', true),
    ('Build full-stack blog application with Next.js and Supabase', true),
    ('Publish first blog post', false)
ON CONFLICT DO NOTHING;

-- Insert Initial Blog Posts
INSERT INTO public.blogs (title, excerpt, content, author_name, category_id, status, tags, likes_count, views_count)
VALUES
    (
        'Getting Started with Next.js and Supabase',
        'Learn how to build modern, server-rendered applications using Next.js App Router and Supabase as the backend database.',
        'Building applications with Next.js and Supabase provides a powerful developer experience. Supabase gives you a full Postgres database with authentication, row-level security, and instant APIs, while Next.js handles server-side rendering, routing, and fast interactive UIs.

## Why Supabase?
Supabase is an open-source Firebase alternative built on PostgreSQL:
- **Instant REST & GraphQL APIs** generated from your tables
- **Built-in Authentication** supporting email/password, magic links, and OAuth providers
- **Row Level Security (RLS)** allowing fine-grained authorization directly in PostgreSQL
- **Realtime Subscriptions** for live updates and chat

## Setting up Next.js with Supabase
Use the `@supabase/ssr` package to handle authentication cookies smoothly across Server Components, Client Components, and Middleware.

Start exploring your new database today!',
        'Alice Johnson',
        (SELECT id FROM public.categories WHERE slug = 'technology' LIMIT 1),
        'published',
        'nextjs, supabase, postgres, tutorial',
        14,
        182
    ),
    (
        'The Art of Modern Web Design in 2026',
        'Exploring the latest trends in web design including glassmorphism, micro-interactions, and modern typography.',
        'Web design has evolved dramatically. Gone are the days of flat, uninspired interfaces. Today''s web experiences are immersive, interactive, and deeply personal.

## Glassmorphism & Beyond
The glassmorphism trend has matured into something more refined. Modern interfaces use subtle transparency and blur effects to create depth without sacrificing readability.

## Micro-Interactions Matter
Every button hover, page transition, and loading state is an opportunity to delight users.',
        'Bob Smith',
        (SELECT id FROM public.categories WHERE slug = 'design' LIMIT 1),
        'published',
        'design, ui, ux, web-design, trends',
        28,
        345
    ),
    (
        'Exploring the Mountains of Nepal',
        'A comprehensive guide to trekking in Nepal — from Everest Base Camp to the Annapurna Circuit.',
        'Nepal is a trekker''s paradise, offering some of the most breathtaking mountain scenery on Earth. From the iconic Everest Base Camp trek to the serene Annapurna Circuit, every trail tells a story.

## Best Time to Visit
The ideal trekking seasons are spring (March-May) and autumn (September-November). During these months, you''ll enjoy clear skies, comfortable temperatures, and the best views.',
        'Alice Johnson',
        (SELECT id FROM public.categories WHERE slug = 'travel' LIMIT 1),
        'published',
        'travel, nepal, trekking, mountains, adventure',
        42,
        512
    )
ON CONFLICT DO NOTHING;
